'use client';
import {useRef,useState} from 'react';
import {ArrowUpRight,Play,Maximize2,X,RotateCcw,Code2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {projects} from './projects';
export default function Gallery(){
 const [selected,setSelected]=useState(projects[0]);const [running,setRunning]=useState(false);const [revision,setRevision]=useState(0);const [ready,setReady]=useState(false);const [fullError,setFullError]=useState('');const workspace=useRef<HTMLDivElement>(null);
 const select=(id:string)=>{setSelected(projects.find(p=>p.id===id)!);setRunning(false);setReady(false);setFullError('');requestAnimationFrame(()=>document.getElementById('project-lab')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'}))};
 const src=`/demos/${selected.id}/index.html`;
 return <><div className="project-grid">{projects.map((p,i)=><article className={'project-card '+(selected.id===p.id?'is-selected':'')} id={p.id} key={p.id}><button className={'project-poster poster-'+p.id} onClick={()=>select(p.id)} aria-label={`Explore ${p.name}`}>{p.image?<img src={p.image} alt={p.caption} loading="lazy" width="800" height="500"/>:<svg viewBox="0 0 800 500" role="img" aria-label="Three-body orbit illustration"><path d="M180 250C180 70 620 70 620 250S180 430 180 250C180 90 620 410 620 250S180 90 180 250" fill="none" stroke="#d7fc70" strokeWidth="2"/><circle cx="180" cy="250" r="9" fill="#d7fc70"/><circle cx="513" cy="162" r="8" fill="#8cd3ee"/><circle cx="520" cy="340" r="8" fill="#eaa6b9"/></svg>}<span className="poster-action">Explore project <ArrowUpRight size={16}/></span></button><div className="card-copy"><p className="eyebrow">0{i+1} / {p.category}</p><h3><button onClick={()=>select(p.id)}>{p.name}</button></h3><p>{p.line}</p><div className="card-bottom"><span>{p.tags.slice(0,2).join(' · ')}</span><span className="interactive-dot">Interactive</span></div></div></article>)}</div>
 <section className="project-lab" id="project-lab" aria-labelledby="lab-title"><div className="lab-heading"><div><p className="eyebrow">THE INTERACTIVE WORKBENCH</p><h3 id="lab-title">{selected.name}</h3></div><p>Explore the actual application.<br/>One project at a time, right here.</p></div><div className="lab-switcher" aria-label="Choose an interactive project">{projects.map(p=><Button key={p.id} variant="ghost" aria-pressed={selected.id===p.id} onClick={()=>{setSelected(p);setRunning(false);setReady(false);setFullError('')}}>{p.name}</Button>)}</div>
 <div className="demo-workspace" ref={workspace}><div className="demo-toolbar"><span className="demo-status"><span className={running?'status-dot active':'status-dot'}/>{running?(ready?'PROJECT OPEN':'LOADING PROJECT…'):'READY TO EXPLORE'}</span><div><a href={src} target="_blank" rel="noopener noreferrer">Open separately <ArrowUpRight size={14}/><span className="sr-only"> (new tab)</span></a>{running&&<><Button variant="ghost" size="sm" aria-label="Restart project" onClick={()=>{setRevision(v=>v+1);setReady(false)}}><RotateCcw size={15}/></Button><Button variant="ghost" size="sm" aria-label="Enter fullscreen" onClick={()=>{if(workspace.current?.requestFullscreen)workspace.current.requestFullscreen().catch(()=>setFullError('Use Open separately for a larger view.'));else setFullError('Use Open separately for a larger view.')}}><Maximize2 size={15}/></Button><Button variant="ghost" size="sm" aria-label="Close project" onClick={()=>{setRunning(false);setReady(false);if(document.fullscreenElement)document.exitFullscreen()}}><X size={16}/></Button></>}</div></div>
 {running?<iframe key={selected.id+revision} src={src} title={`${selected.name} interactive application`} allow="fullscreen" allowFullScreen onLoad={()=>setReady(true)}/>:<div className={'demo-cover cover-'+selected.id}>{selected.image&&<img src={selected.image} alt=""/>}<div className="cover-content"><span className="eyebrow">{selected.category}</span><h4>{selected.line}</h4><p>{selected.tryThis}</p><Button className="launch-button" onClick={()=>{setRunning(true);setReady(false)}}><Play size={17}/>Launch {selected.name}</Button><span className="load-note">Loads on demand · Keyboard and touch controls</span></div></div>}
 </div>{fullError&&<p role="status" className="viewer-note">{fullError}</p>}<p className="viewer-note">{running?selected.tryThis:'Launch to interact, or open separately for more room.'} <span>3D views require WebGL; available fallback views remain usable.</span></p>
 <div className="lab-details"><div><p className="eyebrow">WHAT IT DOES</p><p className="lab-description">{selected.description}</p><div className="tags">{selected.tags.map(t=><span key={t}>{t}</span>)}</div><div className="project-links"><a className="text-link" href={'https://github.com/mattvildibill/'+selected.repo} target="_blank" rel="noopener noreferrer"><Code2 size={16}/>Project repository <ArrowUpRight size={14}/></a><a className="text-link" href={'https://github.com/mattvildibill/matt-vildibill-portfolio/tree/main/public/demos/'+selected.id} target="_blank" rel="noopener noreferrer">Demo implementation <ArrowUpRight size={14}/></a></div></div><div className="engineering"><p className="eyebrow">INSIDE THE BUILD</p>{selected.facts.map((f,i)=><div key={f}><span>0{i+1}</span><p>{f}</p></div>)}</div></div><details className="technical-detail" key={selected.id}><summary>Model boundaries & provenance <span>+</span></summary><p className="boundary">{selected.boundary} Runnable versions of Fabric Lab and the three world projects were recovered from their original hosted source; their initial GitHub exports contained only READMEs.</p></details></section></>
}
