"use client";
import {useEffect,useRef,useState} from 'react';
import {Pause,Play} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
type Orbit={id:string;title:string;positions:number[][][];t:number[]};
export default function Orbit(){
 const canvas=useRef<HTMLCanvasElement>(null);const progress=useRef(.28);const [all,setAll]=useState<Orbit[]>([]);const [mode,setMode]=useState('figure8');const [playing,setPlaying]=useState(true);const [error,setError]=useState(false);
 useEffect(()=>{const c=new AbortController();fetch('/data/orbits.json',{signal:c.signal}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>setAll(data as Orbit[])).catch(e=>{if(e.name!=='AbortError')setError(true)});const m=matchMedia('(prefers-reduced-motion: reduce)');if(m.matches)setPlaying(false);return()=>c.abort()},[]);
 useEffect(()=>{const el=canvas.current;const data=all.find(s=>s.id===mode);if(!el||!data)return;const ctx=el.getContext('2d');if(!ctx)return;let frame=0,phase=progress.current,last=0,visible=true;const colors=['#d7fc70','#8cd3ee','#eaa6b9'];const points=data.positions;let minX=Infinity,maxX=-Infinity,minY=Infinity,maxY=-Infinity;points.forEach(row=>row.forEach(p=>{minX=Math.min(minX,p[0]);maxX=Math.max(maxX,p[0]);minY=Math.min(minY,p[1]);maxY=Math.max(maxY,p[1])}));
 const observer=new IntersectionObserver(([entry])=>visible=entry.isIntersecting);observer.observe(el);
 const draw=(now:number)=>{const dt=last?Math.min(now-last,40):0;last=now;if(playing&&visible&&!document.hidden)phase=(phase+dt/16000)%1;
 const {width:w,height:h}=el.getBoundingClientRect();const dpr=Math.min(devicePixelRatio,2);if(el.width!==Math.round(w*dpr)||el.height!==Math.round(h*dpr)){el.width=Math.round(w*dpr);el.height=Math.round(h*dpr)}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);
 const scale=Math.min(w*.81/(maxX-minX||1),h*.68/(maxY-minY||1));const project=(p:number[])=>[(p[0]-(minX+maxX)/2)*scale+w/2,(p[1]-(minY+maxY)/2)*scale+h/2];
 ctx.strokeStyle='#ffffff09';ctx.lineWidth=1;for(let x=24;x<w;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=20;y<h;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}
 const index=Math.floor(phase*(points.length-1));for(let body=0;body<3;body++){ctx.strokeStyle=colors[body];ctx.globalAlpha=.14;ctx.lineWidth=1.2;ctx.beginPath();points.forEach((row,i)=>{const [x,y]=project(row[body]);if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)});ctx.stroke();ctx.globalAlpha=1;ctx.lineWidth=2;ctx.beginPath();const start=Math.max(0,index-140);for(let k=start;k<=index;k++){const [x,y]=project(points[k][body]);if(k===start)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.stroke();const [x,y]=project(points[index][body]);ctx.fillStyle=colors[body];ctx.shadowColor=colors[body];ctx.shadowBlur=22;ctx.beginPath();ctx.arc(x,y,5,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#f2f4ec';ctx.font='12px monospace';ctx.fillText('0'+(body+1),x+13,y-10)}frame=requestAnimationFrame(draw)};frame=requestAnimationFrame(draw);return()=>{progress.current=phase;cancelAnimationFrame(frame);observer.disconnect()};},[all,mode,playing]);
 return <div className="orbit-panel"><div className="experiment-top"><span className="eyebrow">EXPERIMENT / 001</span><span className="small-muted">Newtonian gravity · G = 1</span></div><canvas ref={canvas} aria-label="Three-body trajectories from Gravity, Unscripted. Lime, blue and pink tracks trace the three bodies." role="img"/>{error&&<p className="orbit-error">Preview unavailable. Open the full experiment below.</p>}<div className="orbit-controls"><Tabs value={mode} onValueChange={setMode}><TabsList aria-label="Orbit experiment"><TabsTrigger value="figure8">Figure eight</TabsTrigger><TabsTrigger value="triangle">Triangle</TabsTrigger><TabsTrigger value="chaos">Burrau</TabsTrigger></TabsList></Tabs><button className="icon-button" onClick={()=>setPlaying(!playing)} aria-label={playing?'Pause animation':'Play animation'}>{playing?<Pause size={16}/>:<Play size={16}/>}</button></div><div className="orbit-caption"><span>Computed trajectories · 2D projection</span><a href="#gravity">Inside the project <span aria-hidden>↗</span></a></div></div>
}
